### PR TITLE
Rupture

### PR DESCRIPTION
**Pull request by emthompson-usgs**

### CODE REVIEW

**Comment by jmfee-usgs** [comment]
Why are these values in parallel arrays, instead of an array of objects?
https://github.com/usgs/shakemap/pull/295/files#diff-1dc908751d7b26ad51ed54a5de1fc682

**Comment by emthompson-usgs** [comment]
@jmfee-usgs This was just a first pass and I hadn't thought about it much yet. Is this what you have in mind?

```
{
  "rupture type": "EdgeRupture",
  "top edge": {
    "latitude": [49.2529, 48.68892, ...],
    "longitude": [-127.64473, -127.0801, ...],
    "depth": [5.0, 5.0, ...]
  },
  "bottom edge": {
    "latitude": [49.79822, 49.38693, ...],
    "longitude": [-126.68793, -125.85895, ...],
    "depth": [26.48063, 30.03475, ...]
  }
}
```

**Comment by jmfee-usgs** [comment]
I was thinking a geojson feature collection of rupture features, where each rupture represents an area that ruptured and may have any number of properties.  Each rupture area could include information about the fault or fault segment that is associated when known:

```
{
    "type": "FeatureCollection",
    "features": [
        {
            "id": 1,
            "type": "Feature",
            "properties": {
                "slip": 1.23,
                "slip-azimuth": 46.7
            },
            "geometry": {
                "type": "Polygon",
                "coordinates": [
                    [
                        [lon0, lat0, depth0],
                        [lon1, lat1, depth1],
                        [lon2, lat2, depth2],
                        [lon0, lat0, depth0]
                    ]
                ]
            }
        }
    ]
}
```

Is there a reason you were tracking the top and bottom edge geometry separately?

**Comment by emthompson-usgs** [comment]
Top and bottom edge information is required for the different types of rupture distance calculations required by GMPEs. Ruptures are more commonly represented as just the top edge (required to be horizontal) along with other orientation information (width, dip, strike). But some geometries do not lend themselves to this format. So we are currently trying to support two rupture representations: 

1. One or more quadrilaterals with horizontal top and bottom edges (this allows for more efficient distance calculations). 
2. The top/bottom edge representation in which neither edge is required to be horizontal. 

The first can fit into the GeoJSON FeatureCollection of polygons (or perhaps it is better to have a single multipolygon feature? I expect this makes more sense in terms of how feature properties are stored). The second would probably make most sense as a FeatureCollection of two LineStrings (or  a single MultiLineString feature). Up until now we have only supported the first option, but this pull request allows for the the second type of rupture representation, which I need to finish the Cascadia scenario. 

For the website, we could add an additional feature that combines the edges into an additional multipolygon feature, but I prefer to avoid redundant data. To get a sense for the level of complexity of these geometric features (and the need for a multiple polygons), please take a look at the ruptures plotted [here](https://github.com/usgs/shakemap/blob/master/notebooks/Read%20and%20display%20UCERF3%20Fault.ipynb) and [here](https://github.com/usgs/shakemap/blob/master/notebooks/Check%20GC2%20coordinate%20calculation.ipynb).

**Pull request merged**
